const translations = {
  de: {
    'nav.services': 'Unsere Leistungen',
    'nav.about': 'Über uns',
    'nav.contact': 'Kontakt',
    'nav.dd.demont': 'Fachgerechte Demontage von Industriemaschinen und -anlagen.',
    'nav.dd.inkoop': 'Wir kaufen Ihre überschüssigen Maschinen und Teile an.',
    'nav.dd.sloopwerk': 'Sichere Abbrucharbeiten an Ihrem Industriestandort.',
    'nav.dd.more': 'Mehr Info ↗',
    'mobile.link1': 'Maschinendemontage',
    'mobile.link2': 'Ankauf von Maschinen & Teilen',
    'mobile.link3': 'Abbrucharbeiten',
    'mobile.link4': 'Über uns',
    'mobile.cta': 'Kontakt',
    'sticky.btn': 'Kontakt aufnehmen',

    'hero.badge': 'Premium Laminat & Parkett',
    'hero.title': 'Böden, die Ihren Wohnraum zum Leben erwecken',
    'hero.sub': 'Entdecken Sie unsere exklusive Kollektion – langlebig, schön und für jeden Wohnraum.',
    'hero.btn': 'Kontakt',
    'hero.secondary': 'Leistungen ansehen',
    'hero.stat': 'Abgeschlossene Projekte',
    'hero.years': 'Jahre Erfahrung',
    'hero.projects': 'Abgeschlossene Projekte',
    'hero.certified': 'Zufriedene Kunden',

    'stats.title': 'Bewährt in der Praxis',
    'stats.sub': 'Jahre industrieller Erfahrung in konkrete Ergebnisse für unsere Kunden umgesetzt.',
    'stats.s1.label': 'Jahre Erfahrung',
    'stats.s1.desc': 'Nachgewiesene Expertise in der Industrie.',
    'stats.s2.label': 'Abgeschlossene Projekte',
    'stats.s2.desc': 'Von der Demontage bis zur vollständigen Fabrikräumung.',
    'stats.s3.label': 'Zufriedene Kunden',
    'stats.s3.desc': 'Wie vereinbart geliefert, jedes Mal.',

    'services.heading': 'Unsere Leistungen',
    'services.tab1': 'Maschinendemontage',
    'services.tab2': 'Ankauf von Maschinen & Teilen',
    'services.tab3': 'Abbrucharbeiten',
    'services.t1.tag': 'Effizient und sicher demontieren',
    'services.t1.title': 'Leise, schnell und ohne Komplikationen',
    'services.t1.text': 'Wir demontieren Industriemaschinen von A bis Z: sicher mit minimaler Unterbrechung, mit voller Verantwortung bis zu Transport und Übergabe.',
    'services.t1.check1': 'Vollständiger Produktionsstopp und schnelle Planung',
    'services.t1.check2': 'Sicher, zertifiziert und plangemäß ausgeführt',
    'services.t1.check3': 'Inkl. Transport, Lagerung oder Weiterverkauf',
    'services.t1.btn': 'Mehr Info',
    'services.t2.tag': 'Maschinen & Teile',
    'services.t2.title': 'Ihre Maschinen verdienen mehr als ein Lager',
    'services.t2.text': 'Wir kaufen gebrauchte Maschinen und Teile an. Direktes Angebot, fairer Preis und schnelle Abwicklung – wir regeln den Rest.',
    'services.t2.check1': 'Schnelle Bewertung und direktes Angebot',
    'services.t2.check2': 'Fairer Marktpreis für Ihre Maschinen',
    'services.t2.check3': 'Wir organisieren Transport und Abholung',
    'services.t2.btn': 'Mehr Info',
    'services.t3.tag': 'Sicher und verantwortungsvoll',
    'services.t3.title': 'Von der Anlage zur leeren Fläche, ohne Sorgen',
    'services.t3.text': 'Professionelle Abbrucharbeiten an Industrieanlagen, durchgeführt von zertifizierten Spezialisten mit minimaler Standzeit.',
    'services.t3.check1': 'Sicher und zertifiziert ausgeführt',
    'services.t3.check2': 'Verantwortungsvolle Verarbeitung und Recycling',
    'services.t3.check3': 'Minimale Störung und maximale Geschwindigkeit',
    'services.t3.btn': 'Mehr Info',

    'usp.eyebrow': 'Qualität, Auswahl und Service aus einer Hand',
    'usp.title': 'Warum WohnStyle?',
    'usp.card1.title': 'Große Auswahl an Dekoren',
    'usp.card1.text': 'Von Eiche über Beton bis hin zu Marmor — wir bieten über 200 Designs für jeden Geschmack und jeden Einrichtungsstil.',
    'usp.card2.title': 'Schnelle Lieferung & Verlegung',
    'usp.card2.text': 'Bestellung heute, Lieferung morgen. Unser professionelles Team verlegt Ihren neuen Boden schnell, sauber und termingerecht.',
    'usp.card3.title': 'Premium Qualität zum fairen Preis',
    'usp.card3.text': 'Langlebige AC4- und AC5-Laminatböden mit 10 Jahren Garantie — für ein schönes Zuhause ohne Kompromisse beim Preis.',

    'svc.usp.title': 'Was wir anders machen',

    'demont.usp1.title': 'Alles aus einer Hand',
    'demont.usp1.text': 'Von der Demontage bis zu Transport und Abwicklung – wir regeln alles ohne Zwischenparteien.',
    'demont.usp2.title': 'Schnelle Ausführung',
    'demont.usp2.text': 'Kurze Wege und direkte Planung sorgen für minimale Standzeiten in Ihrem Betrieb.',
    'demont.usp3.title': 'Maximaler Restwert',
    'demont.usp3.text': 'Wir denken über Wiederverwendung, Weiterverkauf und Recycling nach, um maximale Erträge zu erzielen.',

    'inkoop.usp1.title': 'Schnelle Reaktion',
    'inkoop.usp1.text': 'Direkter Kontakt und ein scharfes Angebot innerhalb von 24 Stunden – ohne lange Verfahren.',
    'inkoop.usp2.title': 'Fairer Marktpreis',
    'inkoop.usp2.text': 'Wir bewerten Ihre Maschinen fair und bieten einen Preis auf Basis des aktuellen Marktwerts.',
    'inkoop.usp3.title': 'Wir organisieren den Transport',
    'inkoop.usp3.text': 'Von der Abholung bis zur vollständigen Abwicklung – Sie müssen sich um nichts kümmern.',

    'sloop.usp1.title': 'Erfahrene Spezialisten',
    'sloop.usp1.text': 'Unser Team verfügt über jahrelange Erfahrung bei Industrieabbrüchen und kennt alle Risiken.',
    'sloop.usp2.title': 'Sicherheit an erster Stelle',
    'sloop.usp2.text': 'Wir arbeiten streng nach Sicherheitsstandards und gehen keine Risiken mit Menschen oder Material ein.',
    'sloop.usp3.title': 'Nachhaltige Verarbeitung',
    'sloop.usp3.text': 'Materialien werden verantwortungsvoll getrennt, recycelt oder weiterverkauft für maximale Wiederverwendung.',

    'footer.services': 'Unsere Leistungen',
    'footer.company': 'Unternehmen',
    'footer.legal': 'Rechtliches',
    'footer.demont': 'Maschinendemontage',
    'footer.inkoop': 'Ankauf von Maschinen & Teilen',
    'footer.sloopwerk': 'Abbrucharbeiten',
    'footer.contact': 'Kontakt',
    'footer.about': 'Über uns',
    'footer.privacy': 'Datenschutzrichtlinie',
    'footer.terms': 'Allgemeine Geschäftsbedingungen',
    'footer.copyright': '© 2026 – Alle Rechte vorbehalten',

    'privacy.title': 'Datenschutzrichtlinie',
    'privacy.updated': 'Zuletzt aktualisiert: Mai 2026',
    'privacy.s1.h2': '1. Einleitung',
    'privacy.s1.p1': 'WohnStyle legt großen Wert auf den Schutz Ihrer personenbezogenen Daten. In dieser Datenschutzrichtlinie erläutern wir, welche Daten wir verarbeiten, warum wir dies tun und welche Rechte Sie als betroffene Person haben.',
    'privacy.s1.p2': 'Wir verarbeiten personenbezogene Daten in Übereinstimmung mit der Datenschutz-Grundverordnung (DSGVO) und sonstigen anwendbaren Datenschutzvorschriften.',
    'privacy.s2.h2': '2. Welche Daten erfassen wir?',
    'privacy.s2.p1': 'Wir verarbeiten ausschließlich Daten, die Sie uns selbst über das Kontaktformular oder per direkter Kommunikation (E-Mail, Telefon) mitteilen. Dazu gehören:',
    'privacy.s2.li1': 'Vor- und Nachname',
    'privacy.s2.li2': 'E-Mail-Adresse',
    'privacy.s2.li3': 'Telefonnummer (falls angegeben)',
    'privacy.s2.li4': 'Firmenname (falls zutreffend)',
    'privacy.s2.li5': 'Der Inhalt Ihrer Nachricht oder Anfrage',
    'privacy.s2.p2': 'Wir erfassen keine besonderen Kategorien personenbezogener Daten (wie Gesundheitsdaten).',
    'privacy.s3.h2': '3. Zwecke der Verarbeitung',
    'privacy.s3.p1': 'Ihre Daten werden für folgende Zwecke verarbeitet:',
    'privacy.s3.li1': 'Beantwortung Ihrer Fragen und Anfragen',
    'privacy.s3.li2': 'Erstellung von Angeboten und Abschluss von Verträgen',
    'privacy.s3.li3': 'Erbringung unserer Dienstleistungen (Demontage, Ankauf, Abbruch)',
    'privacy.s3.li4': 'Erfüllung gesetzlicher Verpflichtungen',
    'privacy.s4.h2': '4. Rechtsgrundlage',
    'privacy.s4.p1': 'Wir verarbeiten Ihre personenbezogenen Daten auf Basis der folgenden Rechtsgrundlagen:',
    'privacy.s4.li1': '<strong>Vertragserfüllung</strong> – wenn Sie uns einen Auftrag erteilen',
    'privacy.s4.li2': '<strong>Berechtigtes Interesse</strong> – zur Bearbeitung Ihrer Kontaktanfrage',
    'privacy.s4.li3': '<strong>Gesetzliche Verpflichtung</strong> – für steuerliche und administrative Zwecke',
    'privacy.s5.h2': '5. Speicherdauer',
    'privacy.s5.p1': 'Wir speichern Ihre personenbezogenen Daten nicht länger als für den jeweiligen Zweck erforderlich. Für geschäftliche Kontaktdaten und Verträge gilt die gesetzliche Aufbewahrungsfrist von sieben Jahren. Kontaktanfragen, aus denen kein Vertrag entstanden ist, werden nach zwei Jahren gelöscht.',
    'privacy.s6.h2': '6. Weitergabe an Dritte',
    'privacy.s6.p1': 'WohnStyle verkauft Ihre personenbezogenen Daten niemals an Dritte. Wir können Daten teilen mit:',
    'privacy.s6.li1': 'Unserem Buchhalter oder Steuerberater für die Finanzbuchhaltung',
    'privacy.s6.li2': 'Behörden, sofern wir gesetzlich dazu verpflichtet sind',
    'privacy.s6.p2': 'Mit Parteien, die Daten in unserem Auftrag verarbeiten, schließen wir einen Auftragsverarbeitungsvertrag gemäß DSGVO ab.',
    'privacy.s7.h2': '7. Ihre Rechte',
    'privacy.s7.p1': 'Gemäß DSGVO haben Sie folgende Rechte bezüglich Ihrer personenbezogenen Daten:',
    'privacy.s7.li1': '<strong>Auskunftsrecht</strong> – Sie können erfragen, welche Daten wir von Ihnen verarbeiten',
    'privacy.s7.li2': '<strong>Berichtigungsrecht</strong> – Sie können die Korrektur unrichtiger Daten verlangen',
    'privacy.s7.li3': '<strong>Löschungsrecht</strong> – Sie können die Löschung Ihrer Daten beantragen',
    'privacy.s7.li4': '<strong>Einschränkungsrecht</strong> – Sie können in bestimmten Fällen die Einschränkung der Verarbeitung verlangen',
    'privacy.s7.li5': '<strong>Datenübertragbarkeit</strong> – Sie können Ihre Daten in einem strukturierten Format anfordern',
    'privacy.s7.li6': '<strong>Widerspruchsrecht</strong> – Sie können der Verarbeitung auf Basis berechtigter Interessen widersprechen',
    'privacy.s7.p2': 'Sie können Ihren Antrag über <a href="contact.html">unser Kontaktformular</a> einreichen. Wir antworten innerhalb von vier Wochen.',
    'privacy.s8.h2': '8. Cookies',
    'privacy.s8.p1': 'Unsere Website verwendet funktionale Cookies, die für den Betrieb der Website unbedingt erforderlich sind (z. B. zur Speicherung Ihrer Spracheinstellung). Wir setzen keine Tracking- oder Werbe-Cookies ein.',
    'privacy.s9.h2': '9. Sicherheit',
    'privacy.s9.p1': 'Wir treffen geeignete technische und organisatorische Maßnahmen, um Ihre personenbezogenen Daten vor Verlust, Missbrauch, unbefugtem Zugriff, Offenlegung oder Veränderung zu schützen.',
    'privacy.s10.h2': '10. Kontakt',
    'privacy.s10.p1': 'Haben Sie Fragen zu dieser Datenschutzrichtlinie? Kontaktieren Sie uns über <a href="contact.html">unser Kontaktformular</a>.',
    'privacy.s10.p2': 'WohnStyle behält sich das Recht vor, diese Datenschutzrichtlinie zu ändern. Änderungen werden auf dieser Seite mit einem neuen Datum veröffentlicht.',

    'terms.title': 'Allgemeine Geschäftsbedingungen',
    'terms.s1.h2': '1. Geltungsbereich',
    'terms.s1.p1': 'Diese Allgemeinen Geschäftsbedingungen gelten für alle Angebote, Kostenvoranschläge und Verträge zwischen WohnStyle und dem Auftraggeber, sofern nicht schriftlich anderes vereinbart wurde.',
    'terms.s2.h2': '2. Angebote',
    'terms.s2.p1': 'Alle Angebote von WohnStyle sind freibleibend und haben eine Gültigkeitsdauer von 30 Tagen, sofern nicht anders angegeben. Preise in Angeboten verstehen sich exklusive Mehrwertsteuer, sofern nicht anders angegeben.',
    'terms.s3.h2': '3. Vertragsschluss',
    'terms.s3.p1': 'Ein Vertrag kommt zustande, wenn WohnStyle den schriftlichen Auftrag des Auftraggebers erhalten und bestätigt hat oder wenn WohnStyle tatsächlich mit der Ausführung des Auftrags begonnen hat.',
    'terms.s4.h2': '4. Auftragsausführung',
    'terms.s4.p1': 'WohnStyle wird den Auftrag nach bestem Wissen und Gewissen ausführen. WohnStyle ist berechtigt, Arbeiten an Dritte zu vergeben, sofern dies für eine ordnungsgemäße Ausführung notwendig ist.',
    'terms.s4.p2': 'Der Auftraggeber sorgt für die rechtzeitige Bereitstellung aller erforderlichen Informationen, Materialien und Zugänge für die Ausführung des Auftrags.',
    'terms.s5.h2': '5. Preise und Zahlung',
    'terms.s5.p1': 'Der vereinbarte Preis versteht sich exklusive Mehrwertsteuer. Die Zahlung hat innerhalb von 14 Tagen nach Rechnungsdatum zu erfolgen, sofern nicht schriftlich anders vereinbart.',
    'terms.s5.p2': 'Bei Überschreitung der Zahlungsfrist ist der Auftraggeber in Verzug und WohnStyle ist berechtigt, die gesetzlichen Verzugszinsen sowie außergerichtliche Inkassokosten in Rechnung zu stellen.',
    'terms.s6.h2': '6. Stornierung',
    'terms.s6.p1': 'Bei Stornierung durch den Auftraggeber ist WohnStyle berechtigt, die bereits entstandenen Kosten in Rechnung zu stellen. Bei Stornierung innerhalb von 5 Werktagen vor Arbeitsbeginn beträgt die Stornogebühr 50 % des vereinbarten Preises.',
    'terms.s7.h2': '7. Haftung',
    'terms.s7.p1': 'Die Haftung von WohnStyle ist auf den Betrag begrenzt, der im jeweiligen Fall von der Haftpflichtversicherung ausgezahlt wird.',
    'terms.s7.p2': 'WohnStyle haftet nicht für indirekte Schäden, Folgeschäden, entgangenen Gewinn oder Schäden durch Betriebsunterbrechung.',
    'terms.s8.h2': '8. Höhere Gewalt',
    'terms.s8.p1': 'Bei höherer Gewalt ist WohnStyle berechtigt, die Ausführung des Auftrags auszusetzen oder den Vertrag aufzulösen, ohne dass der Auftraggeber Anspruch auf Schadensersatz hat.',
    'terms.s9.h2': '9. Geistiges Eigentum',
    'terms.s9.p1': 'Alle von WohnStyle erstellten Dokumente, Berichte und sonstigen Materialien sind und bleiben Eigentum von WohnStyle.',
    'terms.s10.h2': '10. Vertraulichkeit',
    'terms.s10.p1': 'Beide Parteien verpflichten sich zur Geheimhaltung aller vertraulichen Informationen, die sie im Rahmen des Vertrags voneinander erhalten.',
    'terms.s11.h2': '11. Anwendbares Recht und Streitigkeiten',
    'terms.s11.p1': 'Auf alle Vereinbarungen zwischen WohnStyle und dem Auftraggeber ist deutsches Recht anwendbar. Streitigkeiten werden zunächst gütlich beigelegt.',
    'terms.s12.h2': '12. Änderung der Bedingungen',
    'terms.s12.p1': 'WohnStyle behält sich das Recht vor, diese Allgemeinen Geschäftsbedingungen zu ändern. Die aktuellste Version ist stets auf unserer Website verfügbar.',
    'terms.s13.h2': '13. Kontakt',
    'terms.s13.p1': 'Bei Fragen zu diesen Allgemeinen Geschäftsbedingungen kontaktieren Sie uns bitte über <a href="contact.html">unser Kontaktformular</a>.',

    'contact.badge': 'Kontakt',
    'contact.title': 'Kontakt aufnehmen',
    'contact.sub': 'Kontaktieren Sie uns gerne per E-Mail oder nutzen Sie das Kontaktformular. Wir helfen Ihnen gerne weiter.',
    'contact.info.title': 'Unsere Kontaktdaten',
    'contact.info.sub': 'Nutzen Sie eine unserer Kontaktmöglichkeiten',
    'contact.label.email': 'E-Mail',
    'contact.label.phone': 'Telefon',
    'contact.label.address': 'Unser Standort',
    'contact.hours.days': 'Mo – Fr',
    'contact.divider': 'oder',
    'contact.form.title': 'Nutzen Sie unser Formular',
    'contact.form.firstname': 'Vorname',
    'contact.form.lastname': 'Nachname',
    'contact.form.email': 'E-Mail',
    'contact.form.subject': 'Betreff',
    'contact.form.message': 'Nachricht',
    'contact.form.submit': 'Nachricht senden',
    'contact.ph.firstname': 'Max...',
    'contact.ph.lastname': 'Mustermann...',
    'contact.ph.email': 'max@mail.de...',
    'contact.ph.subject': 'Betreff auswählen...',
    'contact.opt.anders': 'Sonstiges',
    'contact.ph.message': 'Schreiben Sie Ihre Nachricht...',

    'demont.title': 'Professionelle Maschinendemontage',
    'demont.sub': 'Wir demontieren Industriemaschinen und -anlagen von A bis Z: sicher mit minimaler Unterbrechung, mit voller Verantwortung bis zu Transport und Übergabe. Das erledigen wir in 2 bis 3 Tagen mit dem gesamten Projekt in der Hand: von der Demontage bis zu Transport und Abnahme.',
    'demont.check1': 'Vollständiger Produktionsstopp und schnelle Planung',
    'demont.check2': 'Sicher, zertifiziert und plangemäß ausgeführt',
    'demont.check3': 'Inkl. Transport, Lagerung oder Weiterverkauf',
    'demont.btn': 'Kontakt aufnehmen',
    'demont.werkwijze': 'Unsere Vorgehensweise',
    'demont.step1.title': 'Bestandsaufnahme und Vorbereitung',
    'demont.step1.text': 'Wir beginnen mit einer Analyse Ihrer Anlage und erfassen alle Maschinen und Risiken.',
    'demont.step2.title': 'Maßnahmenplan',
    'demont.step2.text': 'Wir erstellen einen klaren Zeitplan, der auf Ihren Produktionsprozess abgestimmt ist, um Verluste zu vermeiden.',
    'demont.step3.title': 'Sichere Demontage',
    'demont.step3.text': 'Unsere Spezialisten demontieren die Anlage professionell und gemäß aller Sicherheitsvorschriften.',
    'demont.step4.title': 'Transport und Verarbeitung',
    'demont.step4.text': 'Wir organisieren Transport, Lagerung, Weiterverkauf oder Recycling aller freigewordenen Teile.',
    'demont.step5.title': 'Übergabe',
    'demont.step5.text': 'Der Standort wird ordentlich und wie vereinbart übergeben. Bereit für Ihren nächsten Schritt.',
    'demont.geschikt.tag': 'Für wen ist dies geeignet?',
    'demont.geschikt.title': 'Unsere Demontagen sind geeignet für:',
    'demont.geschikt1': 'Unternehmen, die Maschinen ersetzen oder modernisieren',
    'demont.geschikt2': 'Verlegungen von Produktionsstandorten',
    'demont.geschikt3': 'Betriebsschließung oder Umstrukturierung',
    'demont.geschikt4': 'Überschüssige oder ungenutzte Anlagen',
    'demont.waarom.tag': 'Warum WohnStyle',
    'demont.waarom1': 'Alles aus einer Hand: von der Demontage bis zur Abwicklung',
    'demont.waarom2': 'Schnelle Ausführung mit minimaler Standzeit',
    'demont.waarom3': 'Maximaler Wert aus Ihren Maschinen',
    'demont.cta.title': 'Passend für Ihre Situation?',
    'demont.cta.sub': 'Nehmen Sie Kontakt auf und wir prüfen gemeinsam, ob wir der richtige Partner für Ihr Demontageprojekt sind.',
    'demont.cta.btn': 'Kontakt aufnehmen',

    'inkoop.badge': 'Maschinen & Teile',
    'inkoop.title': 'Ankauf gebrauchter Maschinen & Teile',
    'inkoop.sub': 'Haben Sie überschüssige Maschinen oder Teile? Wir bieten eine schnelle Bewertung, fairen Preis und vollständige Abwicklung – von der Abholung bis zur Verarbeitung.',
    'inkoop.check1': 'Schnelle Bewertung und direktes Angebot',
    'inkoop.check2': 'Fairer Marktpreis für Ihre Maschinen',
    'inkoop.check3': 'Wir organisieren Transport und Abholung',
    'inkoop.btn': 'Angebot anfordern',
    'inkoop.werkwijze': 'Wie läuft der Ankauf ab?',
    'inkoop.step1.title': 'Kontakt aufnehmen',
    'inkoop.step1.text': 'Nehmen Sie Kontakt auf und beschreiben Sie die Maschinen oder Teile, die Sie verkaufen möchten.',
    'inkoop.step2.title': 'Besichtigung & Bewertung',
    'inkoop.step2.text': 'Wir vereinbaren eine Besichtigung oder bewerten auf Basis von Fotos und technischen Spezifikationen.',
    'inkoop.step3.title': 'Angebot & Einigung',
    'inkoop.step3.text': 'Sie erhalten ein unverbindliches Angebot. Bei Einigung planen wir die Abholung sofort.',
    'inkoop.step4.title': 'Abholung & Zahlung',
    'inkoop.step4.text': 'Wir organisieren den Transport und sorgen für eine schnelle und korrekte Abwicklung.',
    'inkoop.geschikt.tag': 'Für wen ist dies geeignet?',
    'inkoop.geschikt.title': 'Wir kaufen an bei:',
    'inkoop.geschikt1': 'Unternehmen, die Maschinen ersetzen oder verkaufen',
    'inkoop.geschikt2': 'Fabriken in Liquidation oder Umstrukturierung',
    'inkoop.geschikt3': 'Behörden und Institutionen mit überschüssigem Material',
    'inkoop.geschikt4': 'Privatpersonen mit Industriemaschinen oder Teilen',
    'inkoop.waarom.tag': 'Warum WohnStyle',
    'inkoop.waarom1': 'Schnelle Reaktion und direktes Angebot',
    'inkoop.waarom2': 'Fairer Preis auf Basis des Marktwerts',
    'inkoop.waarom3': 'Wir regeln alles: Transport, Abholung und Abwicklung',
    'inkoop.cta.title': 'Kommen Ihre Maschinen in Frage?',
    'inkoop.cta.sub': 'Nehmen Sie Kontakt auf und wir teilen Ihnen schnell mit, ob Ihre Maschinen oder Teile in Frage kommen.',
    'inkoop.cta.btn': 'Kontakt aufnehmen',

    'sloop.badge': 'Sicher und verantwortungsvoll',
    'sloop.title': 'Professionelle Industrieabbrüche',
    'sloop.sub': 'Von kleinen Demontagen bis zum vollständigen Abbruch von Industrieanlagen. Wir arbeiten sicher, schnell und mit minimaler Beeinträchtigung Ihres Betriebs.',
    'sloop.check1': 'Sicher und professionell ausgeführt',
    'sloop.check2': 'Verantwortungsvolle Verarbeitung und Recycling',
    'sloop.check3': 'Minimale Störung und maximale Geschwindigkeit',
    'sloop.btn': 'Kontakt aufnehmen',
    'sloop.werkwijze': 'Unsere Vorgehensweise',
    'sloop.step1.title': 'Inspektion & Planung',
    'sloop.step1.text': 'Wir inspizieren den Standort und erstellen einen detaillierten Abbruchplan, der auf Ihre Situation abgestimmt ist.',
    'sloop.step2.title': 'Vorbereitung',
    'sloop.step2.text': 'Alle Anlagen werden überprüft und Sicherheitsmaßnahmen vor Beginn der Arbeiten getroffen.',
    'sloop.step3.title': 'Abbrucharbeiten',
    'sloop.step3.text': 'Professionelle Ausführung durch unser qualifiziertes Team mit Blick auf Sicherheit und Umgebung.',
    'sloop.step4.title': 'Entsorgung & Recycling',
    'sloop.step4.text': 'Materialien werden verantwortungsvoll entsorgt und wo möglich recycelt oder weiterverkauft.',
    'sloop.step5.title': 'Übergabe',
    'sloop.step5.text': 'Der Standort wird ordentlich und wie vereinbart übergeben. Bereit für Ihre nächste Phase.',
    'sloop.geschikt.tag': 'Für wen ist dies geeignet?',
    'sloop.geschikt.title': 'Unsere Abbrucharbeiten sind geeignet für:',
    'sloop.geschikt1': 'Fabriken und Produktionsstandorte',
    'sloop.geschikt2': 'Büros und Gewerbeimmobilien',
    'sloop.geschikt3': 'Infrastrukturprojekte',
    'sloop.geschikt4': 'Gemeinden und Behörden',
    'sloop.waarom.tag': 'Warum WohnStyle',
    'sloop.waarom1': 'Erfahrenes Team mit Fachkenntnissen',
    'sloop.waarom2': 'Sicherheit steht bei uns an erster Stelle',
    'sloop.waarom3': 'Nachhaltige Verarbeitung von Materialien',
    'sloop.cta.title': 'Passend für Ihr Abbruchprojekt?',
    'sloop.cta.sub': 'Nehmen Sie Kontakt auf und wir prüfen gemeinsam, ob wir die richtige Partei für Ihre Situation sind.',
    'sloop.cta.btn': 'Kontakt aufnehmen',

    'about.badge': 'Vertrauenswürdig & erfahren',
    'about.title': 'Über WohnStyle',
    'about.sub': 'Seit mehr als fünf Jahren Ihr zuverlässiger Partner für Maschinendemontage, Ankauf von Industrieequipment und professionelle Abbrucharbeiten.',
    'about.intro': 'WohnStyle wurde aus einer Leidenschaft für die Industrie gegründet. Wir helfen Unternehmen dabei, Industriemaschinen und -anlagen effizient abzustoßen, anzukaufen und zu verarbeiten – mit einem Team, das weiß, was es tut, und zu dem steht, was es verspricht.',
    'about.story.tag': 'Unsere Geschichte',
    'about.story.title': 'Handwerkskunst und Zuverlässigkeit',
    'about.story.text1': 'WohnStyle wurde mit einem Ziel gegründet: Industrieunternehmen bei der Demontage, dem Verkauf und dem Abbruch von Maschinen und Anlagen zu entlasten.',
    'about.story.text2': 'Mit einem erfahrenen Team von Spezialisten und einem pragmatischen Ansatz liefern wir qualitativ hochwertige Arbeit vor Ort – schnell, sicher und wie vereinbart.',
    'about.val.tag': 'Unsere Werte',
    'about.gallery.title': 'Unsere Arbeit im Bild',
    'about.val.title': 'Warum Kunden uns wählen',
    'about.val1.title': 'Zuverlässigkeit',
    'about.val1.text': 'Wir tun, was wir versprechen. Keine Überraschungen, sondern klare Absprachen und ehrliche Kommunikation.',
    'about.val2.title': 'Fachkompetenz',
    'about.val2.text': 'Unsere Spezialisten verfügen über jahrelange Erfahrung in der Industrie und wissen, wie es gemacht wird.',
    'about.val3.title': 'Effizienz',
    'about.val3.text': 'Minimale Standzeiten, maximaler Wert. Wir arbeiten schnell, ohne Abstriche bei der Qualität.',
    'about.cta.title': 'Mit WohnStyle zusammenarbeiten?',
    'about.cta.sub': 'Nehmen Sie Kontakt auf für ein unverbindliches Gespräch über Ihr Projekt.',
    'about.cta.btn': 'Kontakt aufnehmen',

    'divider.text': 'Von Experten ausgewählt — Qualität, die man spürt',

    'section2.tag': 'Unsere Kollektion',
    'section2.title': 'Böden für jeden Raum und jeden Stil',
    'section2.text': 'Von klassischem Eichendekor bis hin zu modernen Grautönen — entdecken Sie unsere handverlesene Auswahl an Premium-Laminat und Parkett für Ihr Zuhause.',

    'testimonial.quote': '"Wir haben unseren kompletten Wohnraum mit dem Laminat von WohnStyle ausgestattet. Die Qualität ist hervorragend und der Service war von Anfang bis Ende erstklassig."',
    'testimonial.name': 'Maria & Thomas Becker',
    'testimonial.role': 'Kunden aus München',

    'cta.text': 'Bereit für Ihren neuen Traumboden? Lassen Sie sich unverbindlich beraten und erhalten Sie Ihr persönliches Angebot.',
    'cta.btn': 'Angebot anfragen',

    'gallery.title': 'Unsere aktuellen Projekte',
    'gallery.sub': 'Entdecken Sie unsere abgeschlossenen Projekte — echte Böden in echten Zuhausen.',
    'gallery.label1': 'Wohnzimmer — Eiche Natur',
    'gallery.label2': 'Schlafzimmer — Grau Modern',
    'gallery.coming': 'Bald verfügbar',

    'hero.btn': 'Angebot anfragen',
    'hero.secondary': 'Kollektion ansehen',
    'sticky.btn': 'Angebot anfragen',
    'mobile.cta': 'Kontakt',
    'nav.contact': 'Kontakt',
    'footer.services': 'Kollektion',
    'footer.demont': 'Laminaat',
    'footer.inkoop': 'Parkett',
    'footer.sloopwerk': 'Vinyl',
    'footer.about': 'Über uns',
    'footer.contact': 'Kontakt',
    'footer.company': 'Unternehmen',
    'footer.legal': 'Rechtliches',
  },

  en: {
    'nav.services': 'Our services',
    'nav.about': 'About Us',
    'nav.contact': 'Contact',
    'nav.dd.demont': 'Professional dismantling of machines and installations.',
    'nav.dd.inkoop': 'We purchase your surplus machines and parts.',
    'nav.dd.sloopwerk': 'Safe demolition work at your industrial site.',
    'nav.dd.more': 'More info ↗',
    'mobile.link1': 'Machine dismantling',
    'mobile.link2': 'Purchase of machines & parts',
    'mobile.link3': 'Demolition work',
    'mobile.link4': 'About Us',
    'mobile.cta': 'Contact',
    'sticky.btn': 'Contact us',

    'hero.badge': 'Premium Laminate & Parquet',
    'hero.title': 'Style Starts at the Floor',
    'hero.sub': 'Discover our exclusive collection – durable, beautiful and for every living space.',
    'hero.btn': 'Contact',
    'hero.secondary': 'View services',
    'hero.stat': 'Projects completed',
    'hero.years': 'Years experience',
    'hero.projects': 'Projects completed',
    'hero.certified': 'Satisfied customers',

    'stats.title': 'Proven in practice',
    'stats.sub': 'Years of industrial experience translated into concrete results for our clients.',
    'stats.s1.label': 'Years experience',
    'stats.s1.desc': 'Proven expertise in the industry.',
    'stats.s2.label': 'Projects completed',
    'stats.s2.desc': 'From dismantling to complete factory clearance.',
    'stats.s3.label': 'Satisfied clients',
    'stats.s3.desc': 'Delivered as agreed, every time.',

    'services.heading': 'Our services',
    'services.tab1': 'Machine dismantling',
    'services.tab2': 'Purchase of machines & parts',
    'services.tab3': 'Demolition work',
    'services.t1.tag': 'Efficient and safe dismantling',
    'services.t1.title': 'Quiet, fast and without any hassle',
    'services.t1.text': 'We dismantle industrial machines from A to Z: safely with minimal disruption, taking full responsibility up to transport and delivery.',
    'services.t1.check1': 'Complete production shutdown and fast planning setup',
    'services.t1.check2': 'Safe, certified and executed according to schedule',
    'services.t1.check3': 'Including transport, storage or resale options',
    'services.t1.btn': 'More info',
    'services.t2.tag': 'Machines & parts',
    'services.t2.title': 'Your machines deserve more than a storage room',
    'services.t2.text': 'We purchase used machines and parts. Direct offer, fair price and fast processing — we handle the rest.',
    'services.t2.check1': 'Quick assessment and direct quote',
    'services.t2.check2': 'Fair market price for your machines',
    'services.t2.check3': 'We arrange transport and collection',
    'services.t2.btn': 'More info',
    'services.t3.tag': 'Safe and responsible',
    'services.t3.title': 'From installation to empty floor, without worries',
    'services.t3.text': 'Professional demolition of industrial installations, carried out by certified specialists with minimal downtime.',
    'services.t3.check1': 'Safe and certified execution',
    'services.t3.check2': 'Responsible processing and recycling',
    'services.t3.check3': 'Minimal disruption and maximum speed',
    'services.t3.btn': 'More info',

    'usp.eyebrow': 'Quality, choice and service from one source',
    'usp.title': 'Why WohnStyle?',
    'usp.card1.title': 'Wide Range of Designs',
    'usp.card1.text': 'From oak to concrete to marble — we offer over 200 designs to suit every taste and interior style.',
    'usp.card2.title': 'Fast Delivery & Installation',
    'usp.card2.text': 'Order today, delivered tomorrow. Our professional team installs your new floor quickly, cleanly and on time.',
    'usp.card3.title': 'Premium Quality at a Fair Price',
    'usp.card3.text': 'Durable AC4 and AC5 laminate floors with a 10-year guarantee — for a beautiful home without compromise on price.',

    'svc.usp.title': 'What we do differently',

    'demont.usp1.title': 'Everything under one roof',
    'demont.usp1.text': 'From dismantling to transport and processing — we handle everything without intermediaries.',
    'demont.usp2.title': 'Fast execution',
    'demont.usp2.text': 'Short lines and direct planning ensure minimal downtime at your company.',
    'demont.usp3.title': 'Maximum residual value',
    'demont.usp3.text': 'We think along about reuse, resale and recycling for maximum returns.',

    'inkoop.usp1.title': 'Fast response',
    'inkoop.usp1.text': 'Direct contact and a sharp quote within 24 hours — without lengthy procedures.',
    'inkoop.usp2.title': 'Fair market price',
    'inkoop.usp2.text': 'We assess your machines fairly and offer a price based on current market value.',
    'inkoop.usp3.title': 'We arrange transport',
    'inkoop.usp3.text': 'From collection to full processing — you do not have to arrange anything yourself.',

    'sloop.usp1.title': 'Experienced specialists',
    'sloop.usp1.text': 'Our team has years of experience in industrial demolition and knows all the risks.',
    'sloop.usp2.title': 'Safety first',
    'sloop.usp2.text': 'We work strictly according to safety standards and take no risks with people or materials.',
    'sloop.usp3.title': 'Sustainable processing',
    'sloop.usp3.text': 'Materials are responsibly separated, recycled or resold for maximum reuse.',

    'footer.services': 'Our services',
    'footer.company': 'Company',
    'footer.legal': 'Legal',
    'footer.demont': 'Machine dismantling',
    'footer.inkoop': 'Purchase of machines & parts',
    'footer.sloopwerk': 'Demolition work',
    'footer.contact': 'Contact',
    'footer.about': 'About Us',
    'footer.privacy': 'Privacy policy',
    'footer.terms': 'Terms and conditions',
    'footer.copyright': '© 2026 – All rights reserved',

    'privacy.title': 'Privacy Policy',
    'privacy.updated': 'Last updated: May 2026',
    'privacy.s1.h2': '1. Introduction',
    'privacy.s1.p1': 'WohnStyle attaches great importance to the protection of your personal data. In this privacy policy, we explain what data we process, why we do so, and what rights you have as a data subject.',
    'privacy.s1.p2': 'We process personal data in accordance with the General Data Protection Regulation (GDPR) and other applicable privacy legislation.',
    'privacy.s2.h2': '2. What data do we collect?',
    'privacy.s2.p1': 'We process only data that you provide to us directly via the contact form or through direct communication (e-mail, phone). This includes:',
    'privacy.s2.li1': 'First and last name',
    'privacy.s2.li2': 'E-mail address',
    'privacy.s2.li3': 'Phone number (if provided)',
    'privacy.s2.li4': 'Company name (if applicable)',
    'privacy.s2.li5': 'The content of your message or request',
    'privacy.s2.p2': 'We do not collect special categories of personal data.',
    'privacy.s3.h2': '3. Purposes of processing',
    'privacy.s3.p1': 'Your data is processed for the following purposes:',
    'privacy.s3.li1': 'Responding to your questions and requests',
    'privacy.s3.li2': 'Issuing quotations and entering into agreements',
    'privacy.s3.li3': 'Performing our services (dismantling, purchasing, demolition)',
    'privacy.s3.li4': 'Complying with legal obligations',
    'privacy.s4.h2': '4. Legal basis',
    'privacy.s4.p1': 'We process your personal data on the basis of the following legal grounds:',
    'privacy.s4.li1': '<strong>Performance of a contract</strong> – when you place an order with us',
    'privacy.s4.li2': '<strong>Legitimate interest</strong> – for handling your contact request',
    'privacy.s4.li3': '<strong>Legal obligation</strong> – for fiscal and administrative purposes',
    'privacy.s5.h2': '5. Retention periods',
    'privacy.s5.p1': 'We do not retain your personal data longer than necessary. For business contacts and agreements, we apply the statutory retention period of seven years.',
    'privacy.s6.h2': '6. Sharing with third parties',
    'privacy.s6.p1': 'WohnStyle never sells your personal data to third parties. We may share data with:',
    'privacy.s6.li1': 'Our bookkeeper or accountant, for financial administration',
    'privacy.s6.li2': 'Government authorities, if we are legally required to do so',
    'privacy.s6.p2': 'With parties that process data on our behalf, we conclude a data processing agreement that complies with the GDPR.',
    'privacy.s7.h2': '7. Your rights',
    'privacy.s7.p1': 'Under the GDPR, you have the following rights with regard to your personal data:',
    'privacy.s7.li1': '<strong>Right of access</strong> – you can request which data we process about you',
    'privacy.s7.li2': '<strong>Right to rectification</strong> – you can have incorrect data corrected',
    'privacy.s7.li3': '<strong>Right to erasure</strong> – you can request that your data be deleted',
    'privacy.s7.li4': '<strong>Right to restriction</strong> – you can have processing restricted in certain cases',
    'privacy.s7.li5': '<strong>Right to portability</strong> – you can request your data in a structured format',
    'privacy.s7.li6': '<strong>Right to object</strong> – you can object to processing based on legitimate interest',
    'privacy.s7.p2': 'You can submit your request via <a href="contact.html">our contact form</a>. We will respond within four weeks.',
    'privacy.s8.h2': '8. Cookies',
    'privacy.s8.p1': 'Our website uses functional cookies that are strictly necessary for the operation of the site. We do not place tracking or advertising cookies.',
    'privacy.s9.h2': '9. Security',
    'privacy.s9.p1': 'We take appropriate technical and organisational measures to protect your personal data against loss, misuse or unauthorised access.',
    'privacy.s10.h2': '10. Contact',
    'privacy.s10.p1': 'Do you have questions about this privacy policy? Please contact us via <a href="contact.html">our contact form</a>.',
    'privacy.s10.p2': 'WohnStyle reserves the right to modify this privacy policy. Changes will be published on this page with a new date.',

    'terms.title': 'Terms and Conditions',
    'terms.s1.h2': '1. Applicability',
    'terms.s1.p1': 'These general terms and conditions apply to all offers, quotations and agreements between WohnStyle and the client, unless otherwise agreed in writing.',
    'terms.s2.h2': '2. Quotations and offers',
    'terms.s2.p1': 'All quotations from WohnStyle are non-binding and valid for 30 days unless otherwise stated. Prices are exclusive of VAT unless otherwise indicated.',
    'terms.s3.h2': '3. Formation of the agreement',
    'terms.s3.p1': 'An agreement is formed when WohnStyle has received and confirmed the client\'s written order, or when WohnStyle has actually commenced execution of the order.',
    'terms.s4.h2': '4. Execution of the assignment',
    'terms.s4.p1': 'WohnStyle will execute the assignment to the best of its knowledge and ability. WohnStyle is entitled to have work carried out by third parties if necessary.',
    'terms.s4.p2': 'The client is responsible for the timely provision of all necessary information, materials and access required for the execution of the assignment.',
    'terms.s5.h2': '5. Prices and payment',
    'terms.s5.p1': 'The agreed price is exclusive of VAT unless expressly stated otherwise. Payment must be made within 14 days of the invoice date.',
    'terms.s5.p2': 'If the payment term is exceeded, the client is in default and WohnStyle is entitled to charge statutory interest as well as extrajudicial collection costs.',
    'terms.s6.h2': '6. Cancellation',
    'terms.s6.p1': 'In the event of cancellation by the client, WohnStyle is entitled to charge costs already incurred. Cancellation within 5 working days before commencement results in a cancellation fee of 50% of the agreed price.',
    'terms.s7.h2': '7. Liability',
    'terms.s7.p1': 'WohnStyle\'s liability is limited to the amount paid out by WohnStyle\'s liability insurance in the relevant case.',
    'terms.s7.p2': 'WohnStyle is not liable for indirect damage, consequential damage, loss of profit or damage due to business interruption.',
    'terms.s8.h2': '8. Force majeure',
    'terms.s8.p1': 'In the event of force majeure, WohnStyle is entitled to suspend execution of the assignment or dissolve the agreement without the client being able to claim compensation.',
    'terms.s9.h2': '9. Intellectual property',
    'terms.s9.p1': 'All documents, reports and other materials produced by WohnStyle are and remain the property of WohnStyle.',
    'terms.s10.h2': '10. Confidentiality',
    'terms.s10.p1': 'Both parties undertake to maintain confidentiality regarding all confidential information received from each other in the context of the agreement.',
    'terms.s11.h2': '11. Applicable law and disputes',
    'terms.s11.p1': 'All agreements between WohnStyle and the client are governed by applicable law. Disputes will first be resolved amicably.',
    'terms.s12.h2': '12. Amendment of terms',
    'terms.s12.p1': 'WohnStyle reserves the right to amend these general terms and conditions. The most current version is always available on our website.',
    'terms.s13.h2': '13. Contact',
    'terms.s13.p1': 'For questions about these general terms and conditions, please contact us via <a href="contact.html">our contact form</a>.',

    'contact.badge': 'Contact',
    'contact.title': 'Get in touch',
    'contact.sub': 'Feel free to contact us by e-mail or use the contact form. We are happy to help you.',
    'contact.info.title': 'Our contact details',
    'contact.info.sub': 'Use one of our contact options',
    'contact.label.email': 'E-mail',
    'contact.label.phone': 'Phone',
    'contact.label.address': 'Our location',
    'contact.hours.days': 'Mon – Fri',
    'contact.divider': 'or',
    'contact.form.title': 'Use our form',
    'contact.form.firstname': 'First name',
    'contact.form.lastname': 'Last name',
    'contact.form.email': 'E-mail',
    'contact.form.subject': 'Subject',
    'contact.form.message': 'Message',
    'contact.form.submit': 'Send message',
    'contact.ph.firstname': 'John...',
    'contact.ph.lastname': 'Smith...',
    'contact.ph.email': 'Smith@mail.com...',
    'contact.ph.subject': 'Select a subject...',
    'contact.opt.anders': 'Other',
    'contact.ph.message': 'Write your message...',

    'demont.title': 'Professional machine dismantling',
    'demont.sub': 'We dismantle industrial machines and installations from A to Z: safely with minimal disruption, taking full responsibility up to transport and delivery.',
    'demont.check1': 'Complete production shutdown and fast planning setup',
    'demont.check2': 'Safe, certified and executed according to schedule',
    'demont.check3': 'Including transport, storage or resale options',
    'demont.btn': 'Contact us',
    'demont.werkwijze': 'Our approach',
    'demont.step1.title': 'Inventory and preparation',
    'demont.step1.text': 'We start with an analysis of your installation and map all machines and risks.',
    'demont.step2.title': 'Plan of action',
    'demont.step2.text': 'We draw up a clear schedule aligned with your production process to avoid losses.',
    'demont.step3.title': 'Safe dismantling',
    'demont.step3.text': 'Our specialists dismantle the installation professionally and according to all safety regulations.',
    'demont.step4.title': 'Transport and processing',
    'demont.step4.text': 'We arrange transport, storage, resale or recycling of all freed components.',
    'demont.step5.title': 'Delivery',
    'demont.step5.text': 'The location is handed over neatly and as agreed. Ready for your next step.',
    'demont.geschikt.tag': 'Who is this suitable for?',
    'demont.geschikt.title': 'Our dismantling services are suitable for:',
    'demont.geschikt1': 'Companies replacing or modernising machines',
    'demont.geschikt2': 'Relocation of production facilities',
    'demont.geschikt3': 'Business closure or reorganisation',
    'demont.geschikt4': 'Surplus or unused installations',
    'demont.waarom.tag': 'Why WohnStyle',
    'demont.waarom1': 'Everything under one roof: from dismantling to processing',
    'demont.waarom2': 'Fast execution with minimal downtime',
    'demont.waarom3': 'Maximum value from your machines',
    'demont.cta.title': 'Suitable for your situation?',
    'demont.cta.sub': 'Contact us and we will assess together whether we are the right partner for your dismantling project.',
    'demont.cta.btn': 'Contact us',

    'inkoop.badge': 'Machines & parts',
    'inkoop.title': 'Purchase of used machines & parts',
    'inkoop.sub': 'Have surplus machines or parts? We offer a quick assessment, fair price and full handling — from collection to processing.',
    'inkoop.check1': 'Quick assessment and direct quote',
    'inkoop.check2': 'Fair market price for your machines',
    'inkoop.check3': 'We arrange transport and collection',
    'inkoop.btn': 'Request a quote',
    'inkoop.werkwijze': 'How does the purchase work?',
    'inkoop.step1.title': 'Get in touch',
    'inkoop.step1.text': 'Contact us and describe the machines or parts you want to sell.',
    'inkoop.step2.title': 'Inspection & assessment',
    'inkoop.step2.text': 'We schedule an inspection or assess based on photos and technical specifications.',
    'inkoop.step3.title': 'Quote & agreement',
    'inkoop.step3.text': 'You receive a no-obligation offer. Upon agreement we schedule collection immediately.',
    'inkoop.step4.title': 'Collection & payment',
    'inkoop.step4.text': 'We arrange transport and ensure a fast and correct settlement.',
    'inkoop.geschikt.tag': 'Who is this suitable for?',
    'inkoop.geschikt.title': 'We purchase from:',
    'inkoop.geschikt1': 'Companies replacing or selling machines',
    'inkoop.geschikt2': 'Factories in liquidation or reorganisation',
    'inkoop.geschikt3': 'Governments and institutions with surplus equipment',
    'inkoop.geschikt4': 'Individuals with industrial machines or parts',
    'inkoop.waarom.tag': 'Why WohnStyle',
    'inkoop.waarom1': 'Fast response and direct quote',
    'inkoop.waarom2': 'Fair price based on market value',
    'inkoop.waarom3': 'We handle everything: transport, collection and processing',
    'inkoop.cta.title': 'Do your machines qualify?',
    'inkoop.cta.sub': 'Contact us and we will quickly let you know whether your machines or parts are eligible.',
    'inkoop.cta.btn': 'Contact us',

    'sloop.badge': 'Safe and responsible',
    'sloop.title': 'Professional industrial demolition work',
    'sloop.sub': 'From small dismantling to full demolition of industrial installations. We work safely, quickly and with minimal disruption to your operations.',
    'sloop.check1': 'Safe and professionally executed',
    'sloop.check2': 'Responsible processing and recycling',
    'sloop.check3': 'Minimal disruption and maximum speed',
    'sloop.btn': 'Contact us',
    'sloop.werkwijze': 'Our approach',
    'sloop.step1.title': 'Inspection & planning',
    'sloop.step1.text': 'We inspect the site and draw up a detailed demolition plan tailored to your situation.',
    'sloop.step2.title': 'Preparation',
    'sloop.step2.text': 'All installations are checked and safety measures taken before work begins.',
    'sloop.step3.title': 'Demolition work',
    'sloop.step3.text': 'Professional execution by our qualified team with attention to safety and surroundings.',
    'sloop.step4.title': 'Removal & recycling',
    'sloop.step4.text': 'Materials are responsibly removed and recycled or resold where possible.',
    'sloop.step5.title': 'Handover',
    'sloop.step5.text': 'The site is handed over neatly and as agreed. Ready for your next phase.',
    'sloop.geschikt.tag': 'Who is this suitable for?',
    'sloop.geschikt.title': 'Our demolition work is suitable for:',
    'sloop.geschikt1': 'Factories and production sites',
    'sloop.geschikt2': 'Offices and commercial premises',
    'sloop.geschikt3': 'Infrastructure projects',
    'sloop.geschikt4': 'Municipalities and government bodies',
    'sloop.waarom.tag': 'Why WohnStyle',
    'sloop.waarom1': 'Experienced team with expertise',
    'sloop.waarom2': 'Safety is our top priority',
    'sloop.waarom3': 'Sustainable processing of materials',
    'sloop.cta.title': 'Suitable for your demolition project?',
    'sloop.cta.sub': 'Contact us and we will assess together whether we are the right party for your situation.',
    'sloop.cta.btn': 'Contact us',

    'about.badge': 'Trusted & Experienced',
    'about.title': 'About WohnStyle',
    'about.sub': 'For over five years your reliable partner for machine dismantling, purchase of industrial equipment and professional demolition work.',
    'about.intro': 'WohnStyle was founded out of a passion for industry. We help companies efficiently divest, purchase and process industrial machines and installations — with a team that knows what it is doing and stands behind what it promises.',
    'about.story.tag': 'Our story',
    'about.story.title': 'Expertise and reliability',
    'about.story.text1': 'WohnStyle was founded with one goal: to relieve industrial companies of the burden of dismantling, selling and demolishing machines and installations.',
    'about.story.text2': 'With an experienced team of specialists and a no-nonsense approach we deliver quality work on site — fast, safe and as agreed.',
    'about.val.tag': 'Our values',
    'about.gallery.title': 'Our work in pictures',
    'about.val.title': 'Why customers choose us',
    'about.val1.title': 'Reliability',
    'about.val1.text': 'We do what we promise. No surprises, just clear agreements and honest communication.',
    'about.val2.title': 'Expertise',
    'about.val2.text': 'Our specialists have years of experience in the industry and know how it should be done.',
    'about.val3.title': 'Efficiency',
    'about.val3.text': 'Minimal downtime, maximum value. We work fast without compromising on quality.',
    'about.cta.title': 'Work with WohnStyle?',
    'about.cta.sub': 'Get in touch for a no-obligation conversation about your project.',
    'about.cta.btn': 'Contact us',

    'divider.text': 'Selected by experts — quality you can feel',

    'section2.tag': 'Our Collection',
    'section2.title': 'Floors for every room and every style',
    'section2.text': 'From classic oak to modern grey tones — discover our hand-picked selection of premium laminate and parquet for your home.',

    'testimonial.quote': '"We renovated our entire home with WohnStyle laminate. The quality is outstanding and the service was first-class from start to finish."',
    'testimonial.name': 'Maria & Thomas Becker',
    'testimonial.role': 'Customers from Munich',

    'cta.text': 'Ready for your new dream floor? Get a free, no-obligation consultation and receive your personal quote.',
    'cta.btn': 'Request a quote',

    'gallery.title': 'See recent projects',
    'gallery.sub': 'Discover our completed projects — real floors in real homes.',
    'gallery.label1': 'Living room — Natural Oak',
    'gallery.label2': 'Bedroom — Modern Grey',
    'gallery.coming': 'Coming soon',

    'hero.btn': 'Request a quote',
    'hero.secondary': 'View collection',
    'sticky.btn': 'Request a quote',
    'mobile.cta': 'Contact',
    'nav.contact': 'Contact',
    'footer.services': 'Collection',
    'footer.demont': 'Laminate',
    'footer.inkoop': 'Parquet',
    'footer.sloopwerk': 'Vinyl',
    'footer.about': 'About us',
    'footer.contact': 'Contact',
    'footer.company': 'Company',
    'footer.legal': 'Legal',
  }
};

const DE_FLAG_SVG = `<path d="M724.515 235.207H27.21C82.8915 97.3045 218.016 0 375.862 0C533.708 0 668.834 97.3045 724.515 235.207Z" fill="black"/><path d="M751.724 375.862C751.724 425.595 742.068 473.072 724.515 516.517H27.2095C9.656 473.072 0 425.595 0 375.862C0 326.129 9.6565 278.652 27.2095 235.206H724.515C742.068 278.652 751.724 326.129 751.724 375.862Z" fill="#DC0000"/><path d="M724.515 516.518C668.834 654.42 533.708 751.724 375.862 751.724C218.016 751.724 82.8915 654.42 27.21 516.518H724.515Z" fill="#FFCE00"/>`;

const flags = {
  de: {
    label: 'DE',
    viewBox: '0 0 752 752', w: '22', h: '22',
    svg: DE_FLAG_SVG
  },
  en: {
    label: 'EN',
    viewBox: '12 12 24 24', w: '22', h: '22',
    svg: `<defs><clipPath id="fl-en-clip"><rect width="23" height="23" fill="white" transform="translate(12.5 12.5)"/></clipPath></defs><g clip-path="url(#fl-en-clip)"><mask id="fl-en-m0" style="mask-type:luminance" maskUnits="userSpaceOnUse" x="12" y="12" width="24" height="24"><path d="M24 35.5C30.3513 35.5 35.5 30.3513 35.5 24C35.5 17.6487 30.3513 12.5 24 12.5C17.6487 12.5 12.5 17.6487 12.5 24C12.5 30.3513 17.6487 35.5 24 35.5Z" fill="white"/></mask><g mask="url(#fl-en-m0)"><path d="M6.61597 11.062H41.3839V36.9096H6.61597V11.062Z" fill="#00247D"/></g><mask id="fl-en-m1" style="mask-type:luminance" maskUnits="userSpaceOnUse" x="12" y="12" width="24" height="24"><path d="M24 35.5C30.3513 35.5 35.5 30.3513 35.5 24C35.5 17.6487 30.3513 12.5 24 12.5C17.6487 12.5 12.5 17.6487 12.5 24C12.5 30.3513 17.6487 35.5 24 35.5Z" fill="white"/></mask><g mask="url(#fl-en-m1)"><path d="M37.4917 36.9095L23.9999 26.8755L10.4985 36.9095H6.61597V34.0128L20.1128 23.9858L6.61597 13.9452V11.062H10.4986L23.9999 21.0959L37.492 11.062H41.3839V13.9447L27.8871 23.9858L41.3839 34.0122V36.9095H37.4917Z" fill="white"/></g><mask id="fl-en-m2" style="mask-type:luminance" maskUnits="userSpaceOnUse" x="12" y="12" width="24" height="24"><path d="M24 35.5C30.3513 35.5 35.5 30.3513 35.5 24C35.5 17.6487 30.3513 12.5 24 12.5C17.6487 12.5 12.5 17.6487 12.5 24C12.5 30.3513 17.6487 35.5 24 35.5Z" fill="white"/></mask><g mask="url(#fl-en-m2)"><path d="M9.20282 36.9095H6.61597L22.7138 24.8697L6.61597 12.9886V11.062L22.7544 22.9852L38.7924 11.062H41.3839L25.2416 22.9886L41.3839 34.983V36.9095L25.3453 24.9121L9.20282 36.9095Z" fill="#CF142B"/></g><mask id="fl-en-m3" style="mask-type:luminance" maskUnits="userSpaceOnUse" x="12" y="12" width="24" height="24"><path d="M24 35.5C30.3513 35.5 35.5 30.3513 35.5 24C35.5 17.6487 30.3513 12.5 24 12.5C17.6487 12.5 12.5 17.6487 12.5 24C12.5 30.3513 17.6487 35.5 24 35.5Z" fill="white"/></mask><g mask="url(#fl-en-m3)"><path d="M27.1558 37.6849H20.8443V27.1414H5.06555V20.8299H20.8443V10.5449H27.1558V20.8299H42.9346V27.1414H27.1558V37.6849Z" fill="white"/></g><mask id="fl-en-m4" style="mask-type:luminance" maskUnits="userSpaceOnUse" x="12" y="12" width="24" height="24"><path d="M24 35.5C30.3513 35.5 35.5 30.3513 35.5 24C35.5 17.6487 30.3513 12.5 24 12.5C17.6487 12.5 12.5 17.6487 12.5 24C12.5 30.3513 17.6487 35.5 24 35.5Z" fill="white"/></mask><g mask="url(#fl-en-m4)"><path d="M25.8935 37.6849H22.1066V25.8792H5.06555V22.0923H22.1066V10.5449H25.8935V22.0923H42.9346V25.8792H25.8935V37.6849Z" fill="#CF142B"/></g></g>`
  }
};

function setLang(lang) {
  localStorage.setItem('lang', lang);
  document.documentElement.lang = lang;

  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (translations[lang] && translations[lang][key]) el.textContent = translations[lang][key];
  });

  document.querySelectorAll('[data-i18n-html]').forEach(el => {
    const key = el.getAttribute('data-i18n-html');
    if (translations[lang] && translations[lang][key]) el.innerHTML = translations[lang][key];
  });

  document.querySelectorAll('[data-i18n-ph]').forEach(el => {
    const key = el.getAttribute('data-i18n-ph');
    if (translations[lang] && translations[lang][key]) el.placeholder = translations[lang][key];
  });

  // Update navbar dropdown
  const flagEl = document.getElementById('activeFlagSvg');
  const labelEl = document.getElementById('activeLangLabel');
  if (flagEl) {
    flagEl.innerHTML = flags[lang].svg;
    flagEl.setAttribute('viewBox', flags[lang].viewBox);
    flagEl.setAttribute('width', flags[lang].w);
    flagEl.setAttribute('height', flags[lang].h);
  }
  if (labelEl) labelEl.textContent = flags[lang].label;
  document.querySelectorAll('.lang-option').forEach(opt => {
    opt.classList.toggle('active', opt.id === 'opt-' + lang);
  });

  // Update footer language label and flag
  const footerLabel = document.getElementById('footerLangLabel');
  if (footerLabel) footerLabel.textContent = lang === 'de' ? 'Deutsch' : 'English';
  const footerFlagEl = document.getElementById('footerActiveFlagSvg');
  if (footerFlagEl) {
    footerFlagEl.innerHTML = flags[lang].svg;
    footerFlagEl.setAttribute('viewBox', flags[lang].viewBox);
    footerFlagEl.setAttribute('width', flags[lang].w);
    footerFlagEl.setAttribute('height', flags[lang].h);
  }
  document.querySelectorAll('.footer-lang-option').forEach(opt => {
    opt.classList.toggle('active', opt.id === 'footer-opt-' + lang);
  });
}

function toggleLangMenu() {
  document.getElementById('langDropdown').classList.toggle('open');
}

function closeLangMenu() {
  document.getElementById('langDropdown').classList.remove('open');
}

function toggleFooterLang() {
  document.getElementById('footerLangDropdown').classList.toggle('open');
}

function closeFooterLang() {
  document.getElementById('footerLangDropdown').classList.remove('open');
}

// Close dropdowns on outside click
document.addEventListener('click', e => {
  const dd = document.getElementById('langDropdown');
  if (dd && !dd.contains(e.target)) dd.classList.remove('open');
  const fdd = document.getElementById('footerLangDropdown');
  if (fdd && !fdd.contains(e.target)) fdd.classList.remove('open');
});

function initLang() {
  const saved = localStorage.getItem('lang') || 'de';
  setLang(saved);
}

document.addEventListener('DOMContentLoaded', initLang);
